[package]
name = "const-str-join"
description = "Small crate to help joining strings during compilation time."
version = "0.2.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/andir/const-str-join"
documentation = "https://docs.rs/const-str-join"

[dependencies]
